BIDDING_IS_NOT_ACTIVE = "BIDDING_IS_NOT_ACTIVE"

BID_PRICE_TOO_LOW = "BID_PRICE_TOO_LOW"

BID_PRICE_BELOW_MINIMUM = "BID_PRICE_BELOW_MINIMUM"

INVALID_TEZ_AMOUNT = "INVALID_TEZ_AMOUNT"

BIDDING_IS_STILL_ACTIVE = "BIDDING_IS_STILL_ACTIVE"

CANNOT_CLAIM = "CANNOT_CLAIM"
